dist: bionic
services:
  - xvfb
addons:
  apt:
    update: true
    packages:
      - libsdl2-dev
      - libassimp-dev
      - mesa-utils
      - linux-generic
      - xserver-xorg-core
      - xserver-xorg
      - xserver-xorg-video-all
      - xserver-xorg-input-all
      - libwayland-egl1-mesa
language: go
before_install:
  - /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX
env:
  global:
    - SDL_VIDEODRIVER=x11
    - DISPLAY=:99.0
  jobs:
    - MESA_GL_VERSION_OVERRIDE=4.3 MESA_GLSL_VERSION_OVERRIDE=430
jobs:
  include:
    - stage: test
      install:
        - go get ./...
      script: go test -v ./...