dist: bionic
services:
  - xvfb
addons:
  apt:
    update: true
    packages:
      - libsdl2-dev
      - libassimp-dev
      - mesa-utils
      - linux-generic
      - xserver-xorg-core
      - xserver-xorg
      - xserver-xorg-video-all
      - xserver-xorg-input-all
      - libwayland-egl1-mesa
      - libgl1-mesa-dev
      - mesa-common-dev
language: go
before_install:
  - /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
  - export SDL_VIDEODRIVER=x11;
  - export DISPLAY=:99.0;
  - sleep 3
install:
  - go get ./...
before_script:
  - glxinfo
script: go test ./...