openGlLogging: true

processingPipeline:
  - shader: phong
    frameBuffer: default
    scene: main

shaders:
  phong:
    type: phong
    vertexShaders:
      - ../Core/Shader/PhongShader/phong.vert
    fragmentShaders:
      - ../Core/Shader/PhongShader/phong.frag
      - ../Core/Shader/PhongShader/material.frag
      - ../Core/Shader/PhongShader/lights.frag

frameBuffers:
  default:
    type: sdlWindow
    config:
      title: YamlConfig Example
      type: window
      width: 800
      height: 800
      depthTest: true
      culling: true

scenes:
  main:
    type: sceneGraph
    config:
      root:
        type: Scene.ParentBaseNode
        children:
          cameraControl:
            type: UI.Control.WASDControl
            config:
              keyboardSensitivity: 1
              mouseSensitivity: 0.5
            transformation:
              - translation: [0, 0, 5]
            children:
              camera:
                type: Node.Camera
                config:
                  perspective:
                    fovy: 90
                    aspect: 1
                    near: 0.1
                    far: 100
                transformation:
                  - rotation:
                      angle: 180
                      axis: [0, 1, 0]
          sunLight:
            type: Node.LightNode.DirectionalLightNode
            config:
              directionalLight:
                ambient: [0.32, 0.32, 0.32]
                diffuse: [0.8, 0.8, 0.8]
                specular: [0.8, 0.8, 0.8]
              initialDirection: [-1, -1, -1]
          arena:
            type: Node.ModelNode
            config:
              file: Models/arena.obj
          construction_light:
            type: Node.ModelNode
            config:
              file: Models/construction_light/construction_light.fbx
              textures:
                diffuse:
                  - Models/construction_light/diffusemap.png
                specular:
                  - Models/construction_light/specular.png
                emissive:
                  - Models/construction_light/glow.png
                normals:
                  - Models/construction_light/normal.png
            transformation:
              - scale: 0.01