openGlLogging: true

shaders:
  phong:
    type: phongShader
    vertexShaders:
      - ../Core/Shader/PhongShader/phong.vert
    fragmentShaders:
      - ../Core/Shader/PhongShader/phong.frag
      - ../Core/Shader/PhongShader/lights.frag
      - ../Core/Model/Material/material.frag
      - ../Core/Light/ShadowMapping/shadow.frag
  postProcessing:
    type: postProcessingShader
    vertexShaders:
      - ../Core/PostProcessing/postProcessing.vert
    fragmentShaders:
      - ../Core/PostProcessing/kernel.frag
  skybox:
    type: skyboxShader
    vertexShaders:
      - ../Core/Skybox/skybox.vert
    fragmentShaders:
      - ../Core/Skybox/skybox.frag
  shadowMapDirectionalLight:
    type: shadowMapShader
    vertexShaders:
      - ../Core/Light/ShadowMapping/DirectionalLight/shadowMap.vert
    fragmentShaders:
      - ../Core/Light/ShadowMapping/DirectionalLight/shadowMap.frag
      - ../Core/Model/Material/material.frag
  shadowMapPointLight:
    type: shadowMapShader
    vertexShaders:
      - ../Core/Light/ShadowMapping/PointLight/shadowMap.vert
    fragmentShaders:
      - ../Core/Light/ShadowMapping/PointLight/shadowMap.frag
      - ../Core/Model/Material/material.frag
    geometryShaders:
      - ../Core/Light/ShadowMapping/PointLight/shadowMap.geom
  shadowMapSpotLight:
    type: shadowMapShader
    vertexShaders:
      - ../Core/Light/ShadowMapping/SpotLight/shadowMap.vert
    fragmentShaders:
      - ../Core/Light/ShadowMapping/SpotLight/shadowMap.frag
      - ../Core/Model/Material/material.frag

scene:
  window:
    title: "YamlConfig Example"
    titlebarFPS: true
    type: window
    sync: false
    width: 1920
    height: 1080
  camera:
    fovy: 45
    near: 0.1
    far: 1000
    uniformBuffer:
      binding: 0
      shaders:
        - phong
        - skybox
  depthTest: true
  culling: true
  blend: true
  children:
    postProcessing:
      type: Node.PostProcessing
      kernel: [
        1, 2, 1,
        2, 4, 2,
        1, 2, 2
      ]
      kernelOffset:
        numerator: 1
        denominator: 300
      kernelMultiplier:
        numerator: 1
        denominator: 16
      shader: postProcessing
      frameBuffer:
        width: 1920
        height: 1080
    cameraControl:
      type: UI.Control.WASDControl
      keyboardSensitivity: 40
      mouseSensitivity: 0.05
      transformation:
        - translation: [0, 10, 100]
      children:
        camera:
          type: Node.Camera
          transformation:
            - rotation:
                angle: 180
                axis: [0, 1, 0]
        flash_light:
          type: Node.LightNode.SpotLightNode
          spotLight:
            innerCone: 12.5
            outerCone: 17.5
            ambient: [0, 0.1, 0]
            diffuse: [0, 1, 0]
            specular: [0, 1, 0]
            linear: 0.014
            quadratic: 0.0007
            direction: [0, 0, 1]
          uniformBuffer:
            binding: 3
            id: spotLight
            shaders:
              - phong
              - shadowMapSpotLight
          shadowMap:
            distance: 325
            shader: shadowMapSpotLight
            frameBuffer:
              width: 1024
              height: 1024
            bindOnShaders:
              - phong
          transformation:
            - rotation:
                angle: 180
                axis: [0, 1, 0]
            - translation: [2, 2, 2]
    sun:
      type: Node.UtilNode.RotorNode
      speed: 0.05
      children:
        sunLight:
          type: Node.LightNode.DirectionalLightNode
          directionalLight:
            direction: [-1, -1, -1]
            ambient: [0.32, 0.32, 0.32]
            diffuse: [0.8, 0.8, 0.8]
            specular: [0.8, 0.8, 0.8]
          uniformBuffer:
            binding: 1
            shaders:
              - phong
              - shadowMapDirectionalLight
          shadowMap:
            distance: 200
            transitionDistance: 20
            shader: shadowMapDirectionalLight
            frameBuffer:
              width: 4096
              height: 4096
            bindOnShaders:
              - phong
    lightRotator:
      type: Node.UtilNode.RotorNode
      speed: 1
      children:
        blueLight:
          type: Node.LightNode.PointLightNode
          pointLight:
            ambient: [0.0, 0.0, 0.2]
            diffuse: [0.0, 0.0, 1.0]
            specular: [0.0, 0.0, 1.0]
            linear: 0.014
            quadratic: 0.0007
          uniformBuffer: pointLight
          transformation:
            - translation: [0, 30, -30]
          shadowMap:
            distance: 192
            shader: shadowMapPointLight
            frameBuffer:
              width: 1024
              height: 1024
            bindOnShaders:
              - phong
        redLight:
          type: Node.LightNode.PointLightNode
          pointLight:
            ambient: [0.2, 0.0, 0.0]
            diffuse: [1.0, 0.0, 0.0]
            specular: [1.0, 0.0, 0.0]
            linear: 0.014
            quadratic: 0.0007
          uniformBuffer:
            id: pointLight
            binding: 2
            shaders:
              - phong
              - shadowMapPointLight
          transformation:
            - translation: [0, 30, 30]
          shadowMap:
            distance: 192
            shader: shadowMapPointLight
            frameBuffer:
              width: 1024
              height: 1024
            bindOnShaders:
              - phong
    skybox:
      type: Node.Skybox
      shader: skybox
      textures:
        back: Models/skybox/back.jpg
        front: Models/skybox/front.jpg
        top: Models/skybox/top.jpg
        bottom: Models/skybox/bottom.jpg
        left: Models/skybox/left.jpg
        right: Models/skybox/right.jpg
    terrain:
      type: Node.TerrainNode
      shader: phong
      file: Models/terrain/heightmap.png
      heightScale: 100
      tileSize: 1
      material:
        blendRange:
          r:
            height: 0.45
            opaqueRange: 0.25
            blendRange: 0.3
          g:
            height: 0.75
            opaqueRange: 0.05
            blendRange: 0.3
          b:
            height: 0.9
            opaqueRange: 0.1
            blendRange: 0.5
        default:
          specularBaseColor: [0.5, 0.5, 0.5]
          uvScale: 50
          textures:
            diffuse: Models/terrain/grass_ground_d.jpg
            normal: Models/terrain/grass_ground_n.jpg
          lodBias: -1
        r:
          uvScale: 50
          textures:
            diffuse: Models/terrain/grass_rocky_d.jpg
            specular: Models/terrain/grass_rocky_s.jpg
            normal: Models/terrain/grass_rocky_n.jpg
          lodBias: -1
        g:
          specularBaseColor: [0.5, 0.5, 0.5]
          uvScale: 50
          textures:
            diffuse: Models/terrain/snow_grass3_d.jpg
            normal: Models/terrain/snow_grass3_n.jpg
          lodBias: -1
        b:
          specularBaseColor: [0.5, 0.5, 0.5]
          uvScale: 50
          textures:
            diffuse: Models/terrain/snow_mntn2_d.jpg
            normal: Models/terrain/snow_mntn2_h.jpg
          lodBias: -1
      children:
        modelPlacements:
          type: Node.ModelNode.ModelPlacementNode
          placementMap: Models/terrain/heightmap.png
          model:
            file: Models/construction_light/Construction_Light.fbx
            material:
              textures:
                diffuse: Models/construction_light/DiffuseMap.png
                specular: Models/construction_light/Specular.png
                emissive: Models/construction_light/Glow.png
                normal: Models/construction_light/Normal.png
              lodBias: -0.7
            shader: phong
            masterMatrix:
              - scale: 0.1
          addToParent: true
        fern1:
          type: Node.ModelNode
          file: Models/fern/fern.fbx
          isTransparent: true
          shader: phong
          transformation:
            - scale: 0.1
          material:
            lodBias: -0.2
        fern2:
          type: Node.ModelNode.ModelSlaveNode
          masterID: terrain.fern1
          transformation:
            - translation: [40, 0, 0]
            - scale: 0.1
        window1:
          type: Node.ModelNode
          file: Models/plain.fbx
          material:
            textures:
              diffuse: Models/blending_transparent_window.png
          isTransparent: true
          shader: phong
          transformation:
            - translation: [0, 0, 50]
            - scale: 0.1
        window2:
          type: Node.ModelNode
          file: Models/plain.fbx
          material:
            textures:
              diffuse: Models/blending_transparent_window.png
          isTransparent: true
          shader: phong
          transformation:
            - translation: [0, 0, 30]
            - scale: 0.1
        construction_light:
          type: Node.ModelNode
          file: Models/construction_light/Construction_Light.fbx
          material:
            textures:
              diffuse: Models/construction_light/DiffuseMap.png
              specular: Models/construction_light/Specular.png
              emissive: Models/construction_light/Glow.png
              normal: Models/construction_light/Normal.png
          shader: phong
          transformation:
            - translation: [0, 0, -50]
            - scale: 0.1
          children:
            light:
              type: Node.LightNode.SpotLightNode
              spotLight:
                innerCone: 12.5
                outerCone: 35
                ambient: [0.05, 0.05, 0.05]
                diffuse: [1, 1, 1]
                specular: [1, 1, 1]
                linear: 0.014
                quadratic: 0.0007
                direction: [0, 0, 1]
              uniformBuffer: spotLight
              shadowMap:
                distance: 325
                shader: shadowMapSpotLight
                frameBuffer:
                  width: 2048
                  height: 2048
                bindOnShaders:
                  - phong
              transformation:
                - rotation:
                    angle: 10
                    axis: [1, 0, 0]
                - translation: [0, 150, 5]