openGlLogging: true

processingPipeline:
  - shader: postProcessing
    frameBuffer: default
    scene: postProcessing
  - shader: phong
    frameBuffer: offScreen
    scene: main

shaders:
  phong:
    type: phong
    vertexShaders:
      - ../Core/Shader/PhongShader/phong.vert
    fragmentShaders:
      - ../Core/Shader/PhongShader/phong.frag
      - ../Core/Shader/PhongShader/material.frag
      - ../Core/Shader/PhongShader/lights.frag
    uniformBuffers:
      - camera
      - directionalLight
  postProcessing:
    type: postProcessing
    vertexShaders:
      - ../Core/PostProcessing/postProcessing.vert
    fragmentShaders:
      - ../Core/PostProcessing/none.frag

frameBuffers:
  default:
    type: sdlWindow
    config:
      title: YamlConfig Example
      type: window
      sync: adaptive
      width: 800
      height: 800
  offScreen:
    type: offScreen
    config:
      width: 800
      height: 800
      depthTest: true
      culling: true
      blend: true

uniformBuffers:
  camera:
    type: camera
    config:
      index: 0
  directionalLight:
    type: directionalLight
    config:
      index: 1

scenes:
  postProcessing:
    type: postProcessing
    config:
      kernel: [
        1, 2, 1,
        2, 4, 2,
        1, 2, 2
      ]
      kernelOffset:
        numerator: 1
        denominator: 300
      kernelMultiplier:
        numerator: 1
        denominator: 16
  main:
    type: sceneGraph
    config:
      root:
        type: Scene.Node
        children:
          cameraControl:
            type: UI.Control.WASDControl
            config:
              keyboardSensitivity: 1
              mouseSensitivity: 0.5
            transformation:
              - translation: [0, 0, 5]
            children:
              camera:
                type: Node.Camera
                config:
                  perspective:
                    fovy: 90
                    aspect: 1
                    near: 0.1
                    far: 100
                  uniformBuffer: camera
                transformation:
                  - rotation:
                      angle: 180
                      axis: [0, 1, 0]
          sunLight:
            type: Node.LightNode.DirectionalLightNode
            config:
              directionalLight:
                direction: [-1, -1, -1]
                ambient: [0.32, 0.32, 0.32]
                diffuse: [0.8, 0.8, 0.8]
                specular: [0.8, 0.8, 0.8]
              uniformBuffer: directionalLight
          arena:
            type: Node.ModelNode
            config:
              file: Models/arena.obj
          fern:
            type: Node.ModelNode
            config:
              file: Models/fern/fern.fbx
            transformation:
              - scale: 0.01
          window1:
            type: Node.ModelNode
            config: &windowConfig
              file: Models/plain.fbx
              textures:
                diffuse:
                  - Models/blending_transparent_window.png
              isTransparent: true
            transformation:
              - translation: [0, 0, 5]
              - scale: 0.01
          window2:
            type: Node.ModelNode
            config: *windowConfig
            transformation:
              - translation: [0, 0, 3]
              - scale: 0.01
